spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5444/main_app_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

server:
  port: 8070

app:
  secret-key: "dlugi_i_sekretny_klucz_do_podpisywania_tokenow"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.web: DEBUG