spring:
  application:
    name: game-service
  datasource:
    url: jdbc:postgresql://localhost:5444/main_app_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8090

app:
  secret-key: "dlugi_i_sekretny_klucz_do_podpisywania_tokenow"
  rawgio-api:
    key: ${RAWGIO_API_KEY}
    uri: https://api.rawg.io/api
