services:
  user-db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user_db
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - "5432:5432"

networks:
  net:
    driver: bridge

volumes:
  user_data:
