services:
  user-db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user_db
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - "5432:5432"

  game-db:
    image: postgres:17
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game
      POSTGRES_DB: game_db
    volumes:
      - game_data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - "5433:5432"

  notification-db:
    image: postgres:17
    environment:
      POSTGRES_USER: notif
      POSTGRES_PASSWORD: notif
      POSTGRES_DB: notification_db
    volumes:
      - notification_data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - "5434:5432"

  activity-db:
    image: postgres:17
    environment:
      POSTGRES_USER: activity
      POSTGRES_PASSWORD: activity
      POSTGRES_DB: activity_db
    volumes:
      - activity_data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - "5435:5432"

  dashboard-db:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: dash
      MONGO_INITDB_ROOT_PASSWORD: dash
      MONGO_INITDB_DATABASE: dashboard_db
    ports:
      - "27017:27017"
    networks:
      - net
    volumes:
      - dashboard_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: amqp-service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
    networks:
      - net

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - APP_SECRET_KEY=dlugi_i_sekretny_klucz_do_podpisywania_tokenow
    depends_on:
      - user-db
    networks:
      - net

  game-service:
    build: ./game-service
    container_name: game-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://game-db:5432/game_db
      - SPRING_DATASOURCE_USERNAME=game
      - SPRING_DATASOURCE_PASSWORD=game
      - SPRING_RABBITMQ_HOST=rabbitmq
      - APP_USER_SERVICE_URL=http://user-service:8080
      - APP_RAWGIO_API_KEY=${RAWGIO_API_KEY}
      - APP_SECRET_KEY=dlugi_i_sekretny_klucz_do_podpisywania_tokenow
    depends_on:
      - game-db
      - rabbitmq
    networks:
      - net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-db:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=notif
      - SPRING_DATASOURCE_PASSWORD=notif
      - SPRING_RABBITMQ_HOST=rabbitmq
      - APP_SECRET_KEY=dlugi_i_sekretny_klucz_do_podpisywania_tokenow
    depends_on:
      - notification-db
      - rabbitmq
    networks:
      - net

  user-insights-service:
    build: ./user-insights-service
    container_name: user-insights-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://activity-db:5432/activity_db
      - SPRING_DATASOURCE_USERNAME=activity
      - SPRING_DATASOURCE_PASSWORD=activity
      - SPRING_DATA_MONGODB_URI=mongodb://dash:dash@dashboard-db:27017/dashboard_db?authSource=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - APP_SECRET_KEY=dlugi_i_sekretny_klucz_do_podpisywania_tokenow
    depends_on:
      - activity-db
      - dashboard-db
      - rabbitmq
    networks:
      - net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "9000:9000"
    environment:
      - FRONTEND_URL=http://localhost:5173
      - USER_SERVICE_URL=http://user-service:8080
      - GAME_SERVICE_URL=http://game-service:8090
      - NOTIFICATION_SERVICE_URL=http://notification-service:8070
    depends_on:
      - user-service
      - game-service
      - notification-service
    networks:
      - net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  user_data:
  game_data:
  notification_data:
  activity_data:
  dashboard_data:
