services:
  app-db-shared:
    image: postgres:17
    container_name: app-db-shared
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main_app_db
    volumes:
      - shared_db_data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - "5444:5432"

  user-service-jdbc:
    build: ./user-service
    container_name: user-service-jdbc
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db-shared:5432/main_app_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - APP_SECRET_KEY=dlugi_i_sekretny_klucz_do_podpisywania_tokenow
    depends_on:
      - app-db-shared
    networks:
      - net

  game-service-jdbc:
    build: ./game-service
    container_name: game-service-jdbc
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db-shared:5432/main_app_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - APP_USER_SERVICE_URL=http://user-service-jdbc:8080
      - APP_RAWGIO_API_KEY=${RAWGIO_API_KEY}
      - APP_SECRET_KEY=dlugi_i_sekretny_klucz_do_podpisywania_tokenow
    depends_on:
      - app-db-shared
      - user-service-jdbc
    networks:
      - net

  notification-service-jdbc:
    build: ./notification-service
    container_name: notification-service-jdbc
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db-shared:5432/main_app_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - APP_SECRET_KEY=dlugi_i_sekretny_klucz_do_podpisywania_tokenow
    depends_on:
      - app-db-shared
      - user-service-jdbc
    networks:
      - net

  gateway-service-jdbc:
    build: ./gateway-service
    container_name: gateway-service-jdbc
    ports:
      - "9000:9000"
    environment:
      - FRONTEND_URL=http://localhost:5173
      - USER_SERVICE_URL=http://user-service-jdbc:8080
      - GAME_SERVICE_URL=http://game-service-jdbc:8090
      - NOTIFICATION_SERVICE_URL=http://notification-service-jdbc:8070
    depends_on:
      - user-service-jdbc
      - game-service-jdbc
      - notification-service-jdbc
    networks:
      - net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  shared_db_data: