spring:
  application:
    name: user-insights-service
  datasource:
    url: jdbc:postgresql://localhost:5435/activity_db
    username: activity
    password: activity
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mongodb:
    uri: mongodb://dash:dash@localhost:27017/dashboard_db?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev
    virtual-host: /

server:
  port: 8060

app:
  secret-key: "dlugi_i_sekretny_klucz_do_podpisywania_tokenow"
  user-service-url: "http://localhost:8080"
  rabbit:
    activity:
      queue: "activity-queue"
      exchange: "activity-exchange"
      routing-key: "add.activity"
    dashboard:
      queue: "dashboard-queue"
      exchange: "dashboard-exchange"
      routing-key: "add.dashboard"
