spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5444/main_app_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    fail-on-missing-locations: true
server:
  port: 8080

app:
  secret-key: "dlugi_i_sekretny_klucz_do_podpisywania_tokenow"

logging:
  level:
    org.flywaydb: DEBUG
